name: Deploy Lambda Functions

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy_lambda.yaml' 
      - 'src/lambda/**'
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-lambda:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Package Lambda
    - name: Package Lambda
      run: |
        cd src/lambda
        pip install -r requirements.txt -t .
        zip -r ../../lambda-deployment.zip .

    # Upload Lambda ZIP to S3
    - name: Upload Lambda ZIP to S3
      run: |
        aws s3 cp lambda-deployment.zip s3://${{ secrets.PROJECT_BUCKET }}/scripts/lambda/lambda-deployment.zip

    # Wait for Lambda to be ready before update
    - name: Wait for Lambda to be ready before update
      run: |
        aws lambda wait function-updated --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --region ${{ secrets.AWS_REGION }}

    # Update Lambda code from S3
    - name: Update Lambda code from S3
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --s3-bucket ${{ secrets.PROJECT_BUCKET }} \
          --s3-key scripts/lambda/lambda-deployment.zip \
          --region ${{ secrets.AWS_REGION }}

    # Wait for Lambda code update to complete
    - name: Wait for Lambda code update to complete
      run: |
        aws lambda wait function-updated --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --region ${{ secrets.AWS_REGION }}

    # Update Lambda configuration
    - name: Update Lambda configuration
      run: |
        aws lambda update-function-configuration \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --environment "Variables={PROJECT_BUCKET=${{ secrets.PROJECT_BUCKET }},LOGS_DATA_PREFIX=logs/}" \
          --region ${{ secrets.AWS_REGION }}