name: Run Data Stream Simulation
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy_simulator.yaml' 
      - 'src/stream_simulator/**'
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4