name: Run Data Stream Simulation
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy_simulator.yaml' 
      - 'src/stream_simulator/**'
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4

        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install boto3 pandas dotenv
      - name: Run stream simulation


        run: |
          python src/stream_simulator/stream_simulate.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          KINESIS_STREAM_NAME: ${{ secrets.KINESIS_STREAM_NAME }}