name: Deploy Lambda Functions

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy_lambda.yaml' 
      - 'src/lambda/**'
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-lambda:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Package Lambda 1
    - name: Package Lambda
      run: |
        cd src/lambda
        pip install -r requirements.txt -t .
        zip -r ../../../lambda-deployment.zip .
        cd ../../../
